remove vlc
fails with 

==> Downloading https://get.videolan.org/vlc/3.0.11/macosx/vlc-3.0.11.dmg
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Download failed on Cask 'vlc' with message: Download failed: https://get.videolan.org/vlc/3.0.11/macosx/vlc-3.0.11.dmg